[book]
authors = [" "]
src = "development_guide"
title = "Lynker Python Development Guide"

[preprocessor.theme]
pagetoc = true
sidebar-width = "250px"

[output.html]
git-repository-url = ""

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false


